### ISSUE TITLE
AssertionError: query not in self.query_to_report

### ISSUE THREAD

**Issue by gogognome** [boxingbeetle/apetest#11]
While using apetest version 0.1.0 on my proprietary project (of which I cannot disclose any details) I got the following AssertionError. I hope the following output of apetests helps in finding the cause of the problem.

```
(env) PS C:\workspace-my-project> apetest -v -v -v localhost:5000 report.html
fetching "robots.txt"...
no "robots.txt" was found
Checking "http://localhost:5000" and below...
checked: 0, to check: 1
INFO: Checking page: localhost:5000
DEBUG:  Found URL: /static/style.css
DEBUG:  Found URL: /auth/register
DEBUG:  Found URL: /auth/login
DEBUG:  Found URL: /
DEBUG:  Found URL: /admin/settings
DEBUG:  Found URL: //ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
checked: 1, to check: 5
INFO: Checking page: localhost:5000/
DEBUG:  Found URL: /static/style.css
DEBUG:  Found URL: /auth/register
DEBUG:  Found URL: /auth/login
DEBUG:  Found URL: /
DEBUG:  Found URL: /admin/settings
DEBUG:  Found URL: //ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\workspace-my-project\env\Scripts\apetest.exe\__main__.py", line 9, in <module>
  File "c:\workspace-my-project\env\lib\site-packages\apetest\cmdline.py", line 144, in main
    return run(args.url, args.report, accept, plugins)
  File "c:\workspace-my-project\env\lib\site-packages\apetest\cmdline.py", line 74, in run
    referrers = checker.check(request)
  File "c:\workspace-my-project\env\lib\site-packages\apetest\checker.py", line 350, in check
    self.scribe.add_report(report)
  File "c:\workspace-my-project\env\lib\site-packages\apetest\report.py", line 303, in add_report
    page.add_report(report)
  File "c:\workspace-my-project\env\lib\site-packages\apetest\report.py", line 222, in add_report
    assert query not in self.query_to_report
AssertionError
```

**Comment by mthuurne** [comment]
The problem seems to be that `localhost:5000` and `localhost:5000/` are treated as separate queries by the spider, while the report collector correctly decides that they are the same query and asserts because it received two reports for the same query.
